name: Build lib

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Western Indonesia Time"
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
          ref: "master"
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      # https://stackoverflow.com/a/61699863/6404439
      # ${{ steps.vars.outputs.branch }}
      # ${{ steps.vars.outputs.hash }}
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"
          echo "::set-output name=yarn::$(yarn cache dir)"
          echo "::set-output name=npm::$(npm config get cache)"

      - name: Resolve git user
        continue-on-error: true
        run: |
          git config user.email "dimaslanjaka@gmail.com"
          git config user.name "dimaslanjaka"
          git fetch --all
          git pull --recurse-submodule
          git submodule update -i -r
          git submodule foreach git submodule update -i -r

      - run: npm i -g gulp-cli ts-node typescript
      - run: npm install
      - run: npm run build

      - name: commit and push
        continue-on-error: true
        run: |
          git add lib
          git commit -m "build from ${{ steps.vars.outputs.hash }}"
          git push origin master
